version: "3.7"
services:
  gastro-app:
    container_name: gastro-app
    restart: always
    build: .
    links:
      - gastro-mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5004:5004"
    environment:
      - SECRET_KEY=df5ea29924d39c3be8785734f13169c6
      - db_service_name=gastro-mongo
      - db_port=385
      - db_name=foodDB
      - PORT=5004
      - DJANGO_SERVER=http://167.71.221.107:8000
      - APP_HOST=http://167.71.221.107:5004
  gastro-mongo:
    image: mongo:latest # use the latest image.
    container_name: gastro-mongo
    restart: always
    environment: # set required env variables to access mongo
      MONGO_INITDB_DATABASE: gastroDB
    command: mongod --port 385
    ports:
      - 385:385
    volumes: # optional to preserve database after container is deleted.
      - ./data/db:/data/db
# volumes:
#   mongo-volume:
  